import Footer from "./components/common/Footer";
import HeroSection from "./components/common/HeroSection";
import Navbar from "./components/common/Navbar";
import SideNavbar from "./components/common/SideNavbar";
import "./globals.css";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body>
        <HeroSection />
        <Navbar />

        <section className="flex w-screen">
              <div className="flex md:w-[20%]">
              <SideNavbar/>
              </div>
              <div className="h-screen md:w-[80%] overflow-scroll hide-scrollbar">
                {children}
              </div>
        </section>

      <Footer/>
      </body>
    </html>
  );
}

