
import "./globals.css";
import WebLayout from "@/app/components/weblayout";


export const metadata = {
  title: "FEMS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <WebLayout children={children} />
      </body>
    </html>
  );
}

