'use client'
import logo from '@/../public/images/logo.jpg'
import Link from 'next/link';
import Image from 'next/image';
import { BsHouse, BsChat, BsList, BsCloudSun, BsShare, BsGear } from "react-icons/bs";
import "./globals.css";
import Herosection from '../components/herosection/page'
import Footer from '../components/footer/page'
import { useState } from 'react';

import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const [menu, setMenu] = useState(false);
  const[msg,setMsg] = useState('');

  const handleSendButtonClick=()=>{
    alert("Searching process done by backend developer\n Thank You :)")
  };

  return (

    <html lang="en">
      <body className={inter.className}>

        <Herosection />
        <div className='w-full flex'>

        {/* left side navigation */}
          <div className='md:w-[20%] md:block md:h-screen w-screen bg-white border-gray-200 md:border-r-2'>
            <div className='flex justify-start p-[8px] md:border-b-2'>
              <button className='text-2xl pr-2 text-[#2d9230] md:hidden  font-extrabold' onClick={() => setMenu(!menu)}>
                <BsList />
              </button>
              <span className='md:pl-2 text-md font-bold text-black'>
              {menu ? 'Navigation': 'Hi, Ramesh 🧑🏻‍🌾🌾'}
              </span>
            </div>

            {/* links in navigation*/}
            <div className={`${menu ? 'block h-screen' : 'hidden'} w-[100%] md:block md:bg-white bg-[#82ff8a]  `}>
              <Link href='/' className='[&.active]:bg-[#3eff4b]'>
                <ul className={`nav-text-style`} onClick={() => setMenu(false)}>
                  <span className='nav-icon-style'><BsHouse /></span>
                  Home
                </ul>
              </Link>

              <Link href='/crop' className='[&.active]:bg-[#3eff4b]'>
                <ul className={`nav-text-style`} onClick={() => setMenu(false)}>
                  <span className='nav-icon-style'><BsChat /></span>
                  Crop
                </ul>
              </Link>


              <Link href='/masterDefination'>
                <ul className={`nav-text-style`} onClick={() => setMenu(false)}>
                  <span className='nav-icon-style'><BsChat /></span>
                  Master Defination
                </ul>
              </Link>


              <Link href='/cropStock'>
                <ul className={`nav-text-style`} onClick={() => setMenu(false)}>
                  <span className='nav-icon-style'><BsChat /></span>
                  Crop Stock
                </ul>
              </Link>


              <Link href='/cropPlanning'>
                <ul className={`nav-text-style`} onClick={() => setMenu(false)}>
                  <span className='nav-icon-style'><BsChat /></span>
                  Crop Planning
                </ul>
              </Link>


              <Link href='/cropRates&Demands'>
                <ul className={`nav-text-style`} onClick={() => setMenu(false)}>
                  <span className='nav-icon-style'><BsChat /></span>
                  Crop Rates & Demands
                </ul>
              </Link>


              <Link href='/cropPositioning'>
                <ul className={`nav-text-style`} onClick={() => setMenu(false)}>
                  <span className='nav-icon-style'><BsChat /></span>
                  Crop Positioning
                </ul>
              </Link>


              <Link href='/cropStatistics'>
                <ul className={`nav-text-style`} onClick={() => setMenu(false)}>
                  <span className='nav-icon-style'><BsChat /></span>
                  Crop Statistics
                </ul>
              </Link>


              <Link href='/income&Expenses'>
                <ul className={`nav-text-style`} onClick={() => setMenu(false)}>
                  <span className='nav-icon-style'><BsChat /></span>
                  Income & Expenses
                </ul>
              </Link>


              <Link href='/Plots'>
                <ul className={`nav-text-style`} onClick={() => setMenu(false)}>
                  <span className='nav-icon-style'><BsChat /></span>
                  Plots
                </ul>
              </Link>


              <Link href='/waterResourses'>
                <ul className={`nav-text-style`} onClick={() => setMenu(false)}>
                  <span className='nav-icon-style'><BsChat /></span>
                  Water Resourses
                </ul>
              </Link>


              <Link href='/manpower&Machinery'>
                <ul className={`nav-text-style`} onClick={() => setMenu(false)}>
                  <span className='nav-icon-style'><BsChat /></span>
                  Manpower & Machinery
                </ul>
              </Link>


              <Link href='/sells&Purchase'>
                <ul className={`nav-text-style`} onClick={() => setMenu(false)}>
                  <span className='nav-icon-style'><BsChat /></span>
                  Sells & Purchase
                </ul>
              </Link>

              <Link href='/setting'>
                <ul className={`nav-text-style`} onClick={() => setMenu(false)}>
                  <span className='nav-icon-style'><BsGear/></span>
                  Setting
                </ul>
              </Link>

            </div>

          </div>
        
        {/* right side navigation + home data [desktop] */}
          <section className='w-[80%] '>
            
            {/* right side navigatin */}
            <div className='w-full h-[40px] md:flex bg-white flex-column justify-between md:p-2 p-1'>

              <div className='md:flex hidden justify-start w-[80%] gap-2'>

                <input 
                type="text"
                placeholder='Search Here..' 
                value={msg}
                onChange={(e) => { setMsg(e.target.value); }}
                         onKeyPress={(e) => {
                          if (e.key === 'Enter') {
                            e.preventDefault();
                            handleSendButtonClick();
                          }
                        }}
                className='text-sm border-2 border-zinc-300 rounded-sm border-b-[#3eff4b] p-3 w-[50%] text-black' />

                <select name="Region" id="region" className='text-sm border-2 border-zinc-300 px-4 border-b-[#3eff4b]  text-neutral-950'>
                  <option value="region1">region</option>
                  <option value="region2">region2</option>
                </select>

                <select name="Language" id="lang" className=' text-sm border-2 border-zinc-300 border-b-[#3eff4b] px-4 text-black'>
                  <option value="lang1">language</option>
                  <option value="lang2">lang2</option>
                </select>

              </div>

              <div className='flex justify-end md:w-[20%] gap-2 '>

                <span className='text-2xl flex items-center justify-center text-blue-500 p-1  rounded-md' title='Weather Info'><BsCloudSun /></span>
                <span className='text-sm flex items-center justify-centertext-black text-black md:p-4 p-2 md:bg-[#3eff4b] font-extrabold  rounded-sm' title="Share to"><BsShare /></span>
                <Image src={logo} alt="" className='w-8 h-8 object-cover rounded-2xl shadow-xl border-1 border-black' title='Account' />

              </div>

            </div>

            {/* home data for desktop */}
            <div className='md:block  hidden'>
              {children}
            </div>
          </section>

        </div>

        {/*home data this part hide and show for mobile devices */}
        <div className={`${menu ? 'hidden' : 'block'} md:hidden  `}>
          {children}
        </div>

        <Footer />

      </body>
    </html>
  );
}









